# -*- coding: utf-8 -*-
"""calculadorasimples.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AXVVMSPMnXjmzNd2jw7iJgMvhI4nXIVF
"""

a=int(input())
c=input()
b=int(input())

if c=="+":
  print(a+b)
elif c=="-":
  print(a-b)
elif c=="x":
  print(a*b)
elif c=="%":
  print(a/b)