# -*- coding: utf-8 -*-
"""comparasequencias.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GvdB0KCEBsiqgTlWq-0YEseBtrxNbPVZ
"""

lista1=[]
lista2=[]

for i in range(0,5):
  lista1.append(int(input()))
i = i+1

for i in range(0,5):
  lista2.append(int(input()))
i = i+1

if lista1==lista2:
  print("As sequencias sao iguais")
else:
  print("As listas sao diferentes")