# -*- coding: utf-8 -*-
"""Cópia de eqsegundograu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12vuZVQC5pENli1_xTuoW2oKGXdf8krJa
"""

import math
a = float(input())
b = float(input())
c = float(input())

delta = float((b*b)-4*a*c)
print(delta)

if delta<0:
  print("Não existe raíz real")
else:
  x1 = float((-b+math.sqrt(delta))/2*a)
  x2 = float((-b-math.sqrt(delta))/2*a)
  print(x1)
  print(x2)