# -*- coding: utf-8 -*-
"""leabrearq.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-KomA6GbX5C9CPLdwXTFQmsrWwTW3gI
"""

menu=0
def abrir():
  arq=open("arquivo.txt","r")
  return arq
def ler(arq):
  linhas=arquivo.readlines()
  for linha in linhas:
    print(linha.strip())
while menu!=3:
  menu = int(input())
  if menu ==1:
    arquivo = abrir()
  elif menu==2:
    ler(arquivo)