# -*- coding: utf-8 -*-
"""multifastpdicionario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MgAIDy6rXGRcmEM0v8cZGwWxVfRZnoU2
"""

arquivo=open("arq.multi-fasta","r")
linhas=arquivo.readlines()
for linha in linhas:
  if linha[0]==">":
    seq=linha.strip()
    dicionario[seq]=""
  else:
    dicionario[seq]=dicionario[seq]+linha.strip()
print(dicionario)