# -*- coding: utf-8 -*-
"""ordemintcresc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nChtZnjiHvz7L2XqsHZJqbNxpn5sWGtY
"""

a=int(input())
b=int(input())
c=int(input())
a1=0
a2=0
a3=0

if a>b and a>c:
  a1=a
  if b>c:
    a2=b
    a3=c
  else:
    a2=c
    a3=b
elif b>a and b>c:
  a1=b
  if a>c:
    a2=a
    a3=c
  else:
    a2=c
    a3=a
elif c>a and c>b:
  a1=c
  if a>b:
    a2=a
    a3=b
  else:
    a2=b
    a3=a

print(a1,a2,a3)