# -*- coding: utf-8 -*-
"""repetiçãosimples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DfczR7YWPCwlvNzFHcJYGSV9p3VSBClH
"""

for i in range(0,2):
  a=int(input())
  if a>6:
     print("aprovado")
  else:
     print("reprovado")
  i=i+1
#     print(i)