# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17eTwjnA7932DjLt80DUJMA78GttNTR2k
"""

print("olá mundo!")