# -*- coding: utf-8 -*-
"""Untitled5.html

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LvYYBvGzjQzIM_Ed11-564T0soZQyHpn
"""

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Produtos - Barbearia Alura</title>
        <link rel="stylesheet" href="produtos.css">
    </head>
    <body>
        <header>
            <h1><img src="logo.png"></h1>

            <ul>
                <li><a>Home</a></li>
                <li>Produtos</li>
                <li>Contato</li>
            </ul>
        </header>
    </body>
</html>