# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13rNMcttBy4uu5fIhPaLssAD3Cwka60Mk
"""

import MySQLdb
host = 127,0,0,1
user = 'root'
password = '12345678'
db = 'escola'
port = 3306
con = MySQLdb.connect(host, user, password, db, port)
c = con.cursor()
def update(tables, field, new_data, where):
  global c, con
  query = "UPDATE "+tables+" SET "+field+" = "+new_data+" WHERE "+where
  c.execute(query)
  return c.fecthall()
print(select('nome, cpf','alunos'))