# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jFCY4OhUWLrHav2AEEl9d72yaRUZE6lf
"""

arquivo = open("arquivo.fasta", "a")
arquivo.write(input())
linhas = arquivo.read()
for linha in linhas:
  print(linha)