# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KjdJiWsiXlnvkJUd8emVQaGpXVK5RTXc
"""

#-*- coding: utf-8 -*-
print("olá mundo!")