# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JrfgXhI2SkI1FM0La9VbpD89OvW2gGbm
"""

seq=input("digite uma sequência")
arquivo=open("seq.fasta", "a+")
arquivo.write(">seq\n")
arquivo.write(seq)
linhas=arquivo.readlines()
for linha in linhas:
  print(linha)