# -*- coding: utf-8 -*-
"""visualização de dados

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KgO4AonRTK2mJKBHIppyfGkTFKnIufhF
"""

import matplotlib.pyplot as plt

x = [1, 3, 5, 7, 9]
y = [2, 3, 7, 1, 0]
z = [200, 25, 400, 3300, 100]
titulo = "Gráfico de dispersão"
eixox = "Eixo X"
eixoy = "Eixo Y"

plt.title(titulo)
plt.xlabel(eixox)
plt.ylabel(eixoy)
plt.scatter(x, y, label = "Meus pontos", color = "k", marker = ".", s=z)
plt.plot(x, y, color = "#000000", linestyle = "--")
plt.legend()
plt.show()
plt.savefig("figura1.png", dpi=300)