# -*- coding: utf-8 -*-
"""voto.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVcnZ-aDx6HVCaVLoPTK-tJQgyiR5UPE
"""

from datetime import date, timedelta
print("insira dia, mês e ano de nascimento")
dia = int(input())
mes = int(input()) 
ano = int(input())

from datetime import date
from dateutil.relativedelta import relativedelta

nascimento = date(ano, mes, dia)
hoje = date.today()
idade = relativedelta(hoje, nascimento)

idade = idade.years
if(idade<=17 and idade>=16):
  print("Voto facultativo")
elif(idade>70):
  print("Voto facultativo")
elif(idade==18):
  print("Você irá votar pela primeira vez, vote com consciência.")
elif(idade>18):
  print("Voto obrigatório")